[build.environment]
  NODE_VERSION = "16"

[build]
  publish = "packages/website/dist"
  command = "turbo run build --filter @valorant-bot/website"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
