name: build

on:
  push:
    branches:
      - main

jobs:
  build-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: v20.11.0
          cache: pnpm

      - run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Deploy bot
        run: pnpm run deploy

      - name: Upload Deploy bot artifacts
        uses: actions/upload-artifact@v4
        with:
          name: deploy-bot-build-files
          path: ./packages/bot/.deploy
          if-no-files-found: error

      - name: Upload Build server artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-server-files
          path: ./packages/server/.output
          if-no-files-found: error

      - name: Upload build website artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-website-files
          path: ./packages/website/dist
          if-no-files-found: error

  deploy-bot:
    needs: build-files
    runs-on: ubuntu-latest
    steps:
      - name: Download deploy bot artifacts
        uses: actions/download-artifact@v4
        with:
          name: deploy-bot-build-files

      - name: Deploy bot to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.BOT_SSH_HOST }}
          username: ${{ secrets.BOT_SSH_USERNAME }}
          password: ${{ secrets.BOT_SSH_PASSWORD }}
          port: ${{ secrets.BOT_SSH_PORT }}
          script: |
            cd /d ${{ secrets.BOT_SSH_DOWNLOADED_PATH }}
            scp -r $GITHUB_WORKSPACE/deploy-bot-build-files.zip ${{ secrets.BOT_SSH_USERNAME }}@${{ secrets.BOT_SSH_HOST }}:${{ secrets.BOT_SSH_DOWNLOADED_PATH }}
